INSERT INTO ROLES ( ROLE_NAME ) VALUES ('Admin')
INSERT INTO ROLES ( ROLE_NAME ) VALUES ('User')
INSERT INTO USERS ( EMAIL, PASSWORD, FIRST_NAME, SURNAME, STATUS) values ('test0@test.com', '$2a$10$30loJpz7J2ESyUueohz8Buvku7j1B6tL0H5CyGSkT0qhtEFTYWFDm','test','test', 'Single' )
INSERT INTO USERS_ROLES ( USER_ID, ROLE_ID ) VALUES (1,1)

